language: scala
scala:
  - 2.11.8
  - 2.10.4
jdk:
  - oraclejdk8
  - openjdk7

sudo: false

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport

after_success:
- bash <(curl -s https://codecov.io/bash)